In [21]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from catboost import CatBoostRegressor

In [22]:
# Load Training Data
# train_df = pd.read_csv("./inputs/train.csv").set_index("id")
%store -r train_df
target = train_df["Listening_Time_minutes"]
train_df.drop("Listening_Time_minutes", axis=1, inplace=True)
train_df

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
id,,,,,,,,,,
0,Mystery Matters,Episode 98,47.042158,True Crime,74.81,Thursday,Night,55.9739,0.0,Positive
1,Joke Junction,Episode 26,119.800000,Comedy,66.95,Saturday,Afternoon,75.9500,2.0,Negative
2,Study Sessions,Episode 16,73.900000,Education,69.97,Tuesday,Evening,8.9700,0.0,Negative
3,Digital Digest,Episode 45,67.170000,Technology,57.22,Monday,Morning,78.7000,2.0,Positive
4,Mind & Body,Episode 86,110.510000,Health,80.07,Monday,Afternoon,58.6800,3.0,Neutral
...,...,...,...,...,...,...,...,...,...,...
749995,Learning Lab,Episode 25,75.660000,Education,69.36,Saturday,Morning,55.9276,0.0,Negative
749996,Business Briefs,Episode 21,75.750000,Business,35.21,Saturday,Night,51.2887,2.0,Neutral
749997,Lifestyle Lounge,Episode 51,30.980000,Lifestyle,78.58,Thursday,Morning,84.8900,0.0,Negative
749998,Style Guide,Episode 47,108.980000,Lifestyle,45.39,Thursday,Morning,93.2700,0.0,Negative
749999,Sports Central,Episode 99,24.100000,Sports,22.45,Saturday,Night,36.7200,0.0,Neutral

In [23]:
# Load Testing Data
# test_df = pd.read_csv("./inputs/test.csv").set_index("id")
%store -r test_df
test_df

,Podcast_Name,Episode_Title,Episode_Length_minutes,Genre,Host_Popularity_percentage,Publication_Day,Publication_Time,Guest_Popularity_percentage,Number_of_Ads,Episode_Sentiment
id,,,,,,,,,,
750000,Educational Nuggets,Episode 73,78.96,Education,38.11,Saturday,Evening,53.3300,1.0,Neutral
750001,Sound Waves,Episode 23,27.87,Music,71.29,Sunday,Morning,42.6747,0.0,Neutral
750002,Joke Junction,Episode 11,69.10,Comedy,67.89,Friday,Evening,97.5100,0.0,Positive
750003,Comedy Corner,Episode 73,115.39,Comedy,23.40,Sunday,Morning,51.7500,2.0,Positive
750004,Life Lessons,Episode 50,72.32,Lifestyle,58.10,Wednesday,Morning,11.3000,2.0,Neutral
...,...,...,...,...,...,...,...,...,...,...
999995,Mind & Body,Episode 100,21.05,Health,65.77,Saturday,Evening,96.4000,3.0,Negative
999996,Joke Junction,Episode 85,85.50,Comedy,41.47,Saturday,Night,30.5200,2.0,Negative
999997,Joke Junction,Episode 63,12.11,Comedy,25.92,Thursday,Evening,73.6900,1.0,Neutral
999998,Market Masters,Episode 46,113.46,Business,43.47,Friday,Night,93.5900,3.0,Positive
999999,Brain Boost,Episode 46,78.05,Education,41.72,Friday,Morning,50.7700,0.0,Negative

In [24]:
# Encode the training categorical columns
%store -r categories
display(categories)
encoder = LabelEncoder()
for column in categories:
    train_df[column] = encoder.fit_transform(train_df[column])

train_df[categories]

Index(['Podcast_Name', 'Episode_Title', 'Genre', 'Publication_Day',
       'Publication_Time', 'Episode_Sentiment'],
      dtype='object')

,Podcast_Name,Episode_Title,Genre,Publication_Day,Publication_Time,Episode_Sentiment
id,,,,,,
0,34,98,9,4,3,2
1,24,19,1,2,0,0
2,40,8,2,5,1,0
3,10,40,8,1,2,2
4,31,85,3,1,0,1
...,...,...,...,...,...,...
749995,26,18,2,2,2,0
749996,2,14,0,2,3,1
749997,28,47,4,4,2,0
749998,41,42,4,4,2,0
749999,38,99,7,2,3,1

In [25]:
# Encode the testing categorical columns
%store -r categories
display(categories)
encoder = LabelEncoder()
for column in categories:
    test_df[column] = encoder.fit_transform(test_df[column])

test_df[categories]

Index(['Podcast_Name', 'Episode_Title', 'Genre', 'Publication_Day',
       'Publication_Time', 'Episode_Sentiment'],
      dtype='object')

,Podcast_Name,Episode_Title,Genre,Publication_Day,Publication_Time,Episode_Sentiment
id,,,,,,
750000,11,71,2,2,1,1
750001,36,16,5,3,2,1
750002,24,3,1,0,1,2
750003,4,71,1,3,2,2
750004,27,46,4,6,2,1
...,...,...,...,...,...,...
999995,31,2,3,2,1,0
999996,24,84,1,2,3,0
999997,24,60,1,4,1,1
999998,29,41,0,0,3,2
999999,1,41,2,0,2,0

In [30]:
# Scale the bot training and testing data
scaler = StandardScaler()
scaled_train = scaler.fit_transform(train_df)
scaled_test = scaler.transform(test_df)

In [31]:
X_train = scaled_train
X_test = scaled_test
y_train = target

In [32]:
# Using CatBoost Regressor
model = CatBoostRegressor()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
predictions

Learning rate set to 0.11653
0:	learn: 24.5399569	total: 45ms	remaining: 45s
1:	learn: 22.2949009	total: 89.4ms	remaining: 44.6s
2:	learn: 20.3486372	total: 135ms	remaining: 45s
3:	learn: 18.6787275	total: 195ms	remaining: 48.4s
4:	learn: 17.2448120	total: 257ms	remaining: 51.1s
5:	learn: 16.0136979	total: 307ms	remaining: 50.9s
6:	learn: 14.9724046	total: 356ms	remaining: 50.4s
7:	learn: 14.0989066	total: 405ms	remaining: 50.2s
8:	learn: 13.3718137	total: 465ms	remaining: 51.2s
9:	learn: 12.7647278	total: 522ms	remaining: 51.7s
10:	learn: 12.2687475	total: 571ms	remaining: 51.4s
11:	learn: 11.8554363	total: 617ms	remaining: 50.8s
12:	learn: 11.5227902	total: 688ms	remaining: 52.3s
13:	learn: 11.2482563	total: 733ms	remaining: 51.6s
14:	learn: 11.0253412	total: 779ms	remaining: 51.1s
15:	learn: 10.8461999	total: 839ms	remaining: 51.6s
16:	learn: 10.7019794	total: 897ms	remaining: 51.9s
17:	learn: 10.5851909	total: 955ms	remaining: 52.1s
18:	learn: 10.4901466	total: 1.01s	remaining: 52.3s
19:	learn: 10.4120235	total: 1.07s	remaining: 52.3s
20:	learn: 10.3501014	total: 1.11s	remaining: 51.9s
21:	learn: 10.3006644	total: 1.16s	remaining: 51.6s
22:	learn: 10.2603209	total: 1.21s	remaining: 51.3s
23:	learn: 10.2264793	total: 1.25s	remaining: 51s
24:	learn: 10.1999930	total: 1.3s	remaining: 50.6s
25:	learn: 10.1780008	total: 1.34s	remaining: 50.4s
26:	learn: 10.1597648	total: 1.39s	remaining: 50.1s
27:	learn: 10.1454581	total: 1.44s	remaining: 50s
28:	learn: 10.1334871	total: 1.48s	remaining: 49.7s
29:	learn: 10.1232757	total: 1.53s	remaining: 49.6s
30:	learn: 10.1150100	total: 1.58s	remaining: 49.6s
31:	learn: 10.1080806	total: 1.63s	remaining: 49.4s
32:	learn: 10.1020618	total: 1.68s	remaining: 49.3s
33:	learn: 10.0972568	total: 1.73s	remaining: 49.2s
34:	learn: 10.0932020	total: 1.78s	remaining: 49s
35:	learn: 10.0898307	total: 1.83s	remaining: 48.9s
36:	learn: 10.0866622	total: 1.88s	remaining: 48.9s
37:	learn: 10.0835511	total: 1.92s	remaining: 48.7s
38:	learn: 10.0810673	total: 1.97s	remaining: 48.4s
39:	learn: 10.0784769	total: 2.01s	remaining: 48.2s
40:	learn: 10.0763923	total: 2.06s	remaining: 48.1s
41:	learn: 10.0740058	total: 2.1s	remaining: 47.8s
42:	learn: 10.0715344	total: 2.14s	remaining: 47.6s
43:	learn: 10.0700999	total: 2.18s	remaining: 47.5s
44:	learn: 10.0686523	total: 2.23s	remaining: 47.3s
45:	learn: 10.0669223	total: 2.27s	remaining: 47.1s
46:	learn: 10.0654156	total: 2.31s	remaining: 46.9s
47:	learn: 10.0641904	total: 2.35s	remaining: 46.7s
48:	learn: 10.0629877	total: 2.4s	remaining: 46.5s
49:	learn: 10.0620187	total: 2.44s	remaining: 46.5s
50:	learn: 10.0609441	total: 2.48s	remaining: 46.2s
51:	learn: 10.0593671	total: 2.53s	remaining: 46.1s
52:	learn: 10.0583072	total: 2.57s	remaining: 45.9s
53:	learn: 10.0574461	total: 2.61s	remaining: 45.8s
54:	learn: 10.0559951	total: 2.66s	remaining: 45.7s
55:	learn: 10.0554349	total: 2.7s	remaining: 45.5s
56:	learn: 10.0544993	total: 2.75s	remaining: 45.4s
57:	learn: 10.0535535	total: 2.79s	remaining: 45.3s
58:	learn: 10.0526998	total: 2.83s	remaining: 45.2s
59:	learn: 10.0523035	total: 2.88s	remaining: 45.2s
60:	learn: 10.0518143	total: 2.94s	remaining: 45.3s
61:	learn: 10.0511314	total: 2.99s	remaining: 45.2s
62:	learn: 10.0502398	total: 3.04s	remaining: 45.1s
63:	learn: 10.0490000	total: 3.09s	remaining: 45.1s
64:	learn: 10.0482967	total: 3.13s	remaining: 45s
65:	learn: 10.0478272	total: 3.17s	remaining: 44.9s
66:	learn: 10.0474905	total: 3.21s	remaining: 44.7s
67:	learn: 10.0472073	total: 3.25s	remaining: 44.6s
68:	learn: 10.0461055	total: 3.29s	remaining: 44.5s
69:	learn: 10.0456190	total: 3.34s	remaining: 44.4s
70:	learn: 10.0445284	total: 3.38s	remaining: 44.2s
71:	learn: 10.0438847	total: 3.42s	remaining: 44s
72:	learn: 10.0431188	total: 3.46s	remaining: 44s
73:	learn: 10.0424798	total: 3.5s	remaining: 43.9s
74:	learn: 10.0416832	total: 3.54s	remaining: 43.7s
75:	learn: 10.0410797	total: 3.59s	remaining: 43.6s
76:	learn: 10.0403458	total: 3.63s	remaining: 43.5s
77:	learn: 10.0396727	total: 3.67s	remaining: 43.4s
78:	learn: 10.0393644	total: 3.71s	remaining: 43.2s
79:	learn: 10.0389431	total: 3.74s	remaining: 43.1s
80:	learn: 10.0382409	total: 3.79s	remaining: 43s
81:	learn: 10.0371696	total: 3.84s	remaining: 43s
82:	learn: 10.0367414	total: 3.88s	remaining: 42.9s
83:	learn: 10.0361690	total: 3.92s	remaining: 42.8s
84:	learn: 10.0355874	total: 3.96s	remaining: 42.6s
85:	learn: 10.0347649	total: 4s	remaining: 42.5s
86:	learn: 10.0344606	total: 4.04s	remaining: 42.4s
87:	learn: 10.0340368	total: 4.09s	remaining: 42.4s
88:	learn: 10.0336601	total: 4.13s	remaining: 42.3s
89:	learn: 10.0331393	total: 4.18s	remaining: 42.2s
90:	learn: 10.0324409	total: 4.22s	remaining: 42.2s
91:	learn: 10.0321435	total: 4.27s	remaining: 42.1s
92:	learn: 10.0313372	total: 4.31s	remaining: 42.1s
93:	learn: 10.0304879	total: 4.36s	remaining: 42s
94:	learn: 10.0301769	total: 4.39s	remaining: 41.8s
95:	learn: 10.0295580	total: 4.43s	remaining: 41.8s
96:	learn: 10.0291035	total: 4.48s	remaining: 41.7s
97:	learn: 10.0284861	total: 4.52s	remaining: 41.6s
98:	learn: 10.0279633	total: 4.56s	remaining: 41.5s
99:	learn: 10.0273050	total: 4.6s	remaining: 41.4s
100:	learn: 10.0266188	total: 4.64s	remaining: 41.3s
101:	learn: 10.0261940	total: 4.69s	remaining: 41.3s
102:	learn: 10.0257087	total: 4.73s	remaining: 41.2s
103:	learn: 10.0252076	total: 4.77s	remaining: 41.1s
104:	learn: 10.0242931	total: 4.82s	remaining: 41.1s
105:	learn: 10.0239017	total: 4.86s	remaining: 41s
106:	learn: 10.0235254	total: 4.9s	remaining: 40.9s
107:	learn: 10.0231166	total: 4.95s	remaining: 40.9s
108:	learn: 10.0227811	total: 4.99s	remaining: 40.8s
109:	learn: 10.0223872	total: 5.03s	remaining: 40.7s
110:	learn: 10.0217176	total: 5.07s	remaining: 40.6s
111:	learn: 10.0213085	total: 5.11s	remaining: 40.5s
112:	learn: 10.0206316	total: 5.15s	remaining: 40.4s
113:	learn: 10.0202682	total: 5.2s	remaining: 40.4s
114:	learn: 10.0199430	total: 5.24s	remaining: 40.3s
115:	learn: 10.0192877	total: 5.28s	remaining: 40.2s
116:	learn: 10.0187893	total: 5.32s	remaining: 40.2s
117:	learn: 10.0181374	total: 5.36s	remaining: 40.1s
118:	learn: 10.0174659	total: 5.41s	remaining: 40s
119:	learn: 10.0168754	total: 5.45s	remaining: 40s
120:	learn: 10.0162133	total: 5.49s	remaining: 39.9s
121:	learn: 10.0155229	total: 5.54s	remaining: 39.8s
122:	learn: 10.0147906	total: 5.57s	remaining: 39.7s
123:	learn: 10.0143039	total: 5.62s	remaining: 39.7s
124:	learn: 10.0136432	total: 5.66s	remaining: 39.6s
125:	learn: 10.0132680	total: 5.71s	remaining: 39.6s
126:	learn: 10.0126646	total: 5.75s	remaining: 39.5s
127:	learn: 10.0121403	total: 5.79s	remaining: 39.5s
128:	learn: 10.0115053	total: 5.83s	remaining: 39.4s
129:	learn: 10.0111722	total: 5.87s	remaining: 39.3s
130:	learn: 10.0105067	total: 5.92s	remaining: 39.2s
131:	learn: 10.0097822	total: 5.96s	remaining: 39.2s
132:	learn: 10.0091828	total: 6.01s	remaining: 39.2s
133:	learn: 10.0086508	total: 6.05s	remaining: 39.1s
134:	learn: 10.0083406	total: 6.09s	remaining: 39s
135:	learn: 10.0079068	total: 6.13s	remaining: 38.9s
136:	learn: 10.0074616	total: 6.17s	remaining: 38.9s
137:	learn: 10.0069038	total: 6.22s	remaining: 38.8s
138:	learn: 10.0064929	total: 6.25s	remaining: 38.7s
139:	learn: 10.0058025	total: 6.3s	remaining: 38.7s
140:	learn: 10.0052178	total: 6.35s	remaining: 38.7s
141:	learn: 10.0046210	total: 6.4s	remaining: 38.7s
142:	learn: 10.0041380	total: 6.44s	remaining: 38.6s
143:	learn: 10.0038153	total: 6.48s	remaining: 38.5s
144:	learn: 10.0032720	total: 6.52s	remaining: 38.5s
145:	learn: 10.0028592	total: 6.57s	remaining: 38.4s
146:	learn: 10.0023676	total: 6.61s	remaining: 38.4s
147:	learn: 10.0019527	total: 6.66s	remaining: 38.3s
148:	learn: 10.0014273	total: 6.7s	remaining: 38.3s
149:	learn: 10.0008887	total: 6.74s	remaining: 38.2s
150:	learn: 10.0005551	total: 6.79s	remaining: 38.2s
151:	learn: 10.0003120	total: 6.83s	remaining: 38.1s
152:	learn: 10.0000176	total: 6.87s	remaining: 38s
153:	learn: 9.9994815	total: 6.91s	remaining: 37.9s
154:	learn: 9.9989292	total: 6.95s	remaining: 37.9s
155:	learn: 9.9983736	total: 7s	remaining: 37.9s
156:	learn: 9.9976861	total: 7.04s	remaining: 37.8s
157:	learn: 9.9971890	total: 7.09s	remaining: 37.8s
158:	learn: 9.9967965	total: 7.13s	remaining: 37.7s
159:	learn: 9.9962574	total: 7.17s	remaining: 37.7s
160:	learn: 9.9958656	total: 7.21s	remaining: 37.6s
161:	learn: 9.9954122	total: 7.28s	remaining: 37.6s
162:	learn: 9.9950347	total: 7.31s	remaining: 37.5s
163:	learn: 9.9946167	total: 7.35s	remaining: 37.5s
164:	learn: 9.9941855	total: 7.39s	remaining: 37.4s
165:	learn: 9.9936499	total: 7.44s	remaining: 37.4s
166:	learn: 9.9933650	total: 7.48s	remaining: 37.3s
167:	learn: 9.9929175	total: 7.53s	remaining: 37.3s
168:	learn: 9.9925738	total: 7.57s	remaining: 37.2s
169:	learn: 9.9920502	total: 7.61s	remaining: 37.2s
170:	learn: 9.9915063	total: 7.66s	remaining: 37.1s
171:	learn: 9.9911183	total: 7.72s	remaining: 37.1s
172:	learn: 9.9907282	total: 7.79s	remaining: 37.2s
173:	learn: 9.9900476	total: 7.86s	remaining: 37.3s
174:	learn: 9.9896762	total: 7.92s	remaining: 37.3s
175:	learn: 9.9891989	total: 7.96s	remaining: 37.3s
176:	learn: 9.9888513	total: 8.01s	remaining: 37.3s
177:	learn: 9.9885345	total: 8.06s	remaining: 37.2s
178:	learn: 9.9880402	total: 8.11s	remaining: 37.2s
179:	learn: 9.9876160	total: 8.17s	remaining: 37.2s
180:	learn: 9.9872755	total: 8.22s	remaining: 37.2s
181:	learn: 9.9869335	total: 8.28s	remaining: 37.2s
182:	learn: 9.9863015	total: 8.34s	remaining: 37.2s
183:	learn: 9.9859050	total: 8.4s	remaining: 37.2s
184:	learn: 9.9855662	total: 8.45s	remaining: 37.2s
185:	learn: 9.9850506	total: 8.49s	remaining: 37.2s
186:	learn: 9.9844762	total: 8.54s	remaining: 37.1s
187:	learn: 9.9841659	total: 8.59s	remaining: 37.1s
188:	learn: 9.9838200	total: 8.64s	remaining: 37.1s
189:	learn: 9.9833775	total: 8.69s	remaining: 37s
190:	learn: 9.9829103	total: 8.73s	remaining: 37s
191:	learn: 9.9825237	total: 8.78s	remaining: 36.9s
192:	learn: 9.9821007	total: 8.83s	remaining: 36.9s
193:	learn: 9.9815174	total: 8.88s	remaining: 36.9s
194:	learn: 9.9810868	total: 8.93s	remaining: 36.9s
195:	learn: 9.9807527	total: 8.98s	remaining: 36.8s
196:	learn: 9.9804080	total: 9.03s	remaining: 36.8s
197:	learn: 9.9801341	total: 9.08s	remaining: 36.8s
198:	learn: 9.9797282	total: 9.13s	remaining: 36.7s
199:	learn: 9.9793576	total: 9.17s	remaining: 36.7s
200:	learn: 9.9791570	total: 9.22s	remaining: 36.6s
201:	learn: 9.9786778	total: 9.26s	remaining: 36.6s
202:	learn: 9.9782627	total: 9.31s	remaining: 36.6s
203:	learn: 9.9779013	total: 9.37s	remaining: 36.6s
204:	learn: 9.9775007	total: 9.41s	remaining: 36.5s
205:	learn: 9.9765974	total: 9.46s	remaining: 36.5s
206:	learn: 9.9763339	total: 9.5s	remaining: 36.4s
207:	learn: 9.9759661	total: 9.54s	remaining: 36.3s
208:	learn: 9.9755466	total: 9.59s	remaining: 36.3s
209:	learn: 9.9752383	total: 9.63s	remaining: 36.2s
210:	learn: 9.9748570	total: 9.68s	remaining: 36.2s
211:	learn: 9.9746318	total: 9.71s	remaining: 36.1s
212:	learn: 9.9741877	total: 9.75s	remaining: 36s
213:	learn: 9.9739073	total: 9.79s	remaining: 36s
214:	learn: 9.9735564	total: 9.84s	remaining: 35.9s
215:	learn: 9.9731894	total: 9.88s	remaining: 35.9s
216:	learn: 9.9729079	total: 9.94s	remaining: 35.9s
217:	learn: 9.9726261	total: 9.98s	remaining: 35.8s
218:	learn: 9.9722601	total: 10s	remaining: 35.8s
219:	learn: 9.9718958	total: 10.1s	remaining: 35.7s
220:	learn: 9.9714477	total: 10.1s	remaining: 35.7s
221:	learn: 9.9712133	total: 10.2s	remaining: 35.7s
222:	learn: 9.9709999	total: 10.2s	remaining: 35.7s
223:	learn: 9.9705529	total: 10.3s	remaining: 35.7s
224:	learn: 9.9700942	total: 10.4s	remaining: 35.7s
225:	learn: 9.9696774	total: 10.4s	remaining: 35.7s
226:	learn: 9.9691073	total: 10.5s	remaining: 35.8s
227:	learn: 9.9688411	total: 10.6s	remaining: 35.8s
228:	learn: 9.9684548	total: 10.6s	remaining: 35.8s
229:	learn: 9.9679284	total: 10.7s	remaining: 35.8s
230:	learn: 9.9675579	total: 10.7s	remaining: 35.8s
231:	learn: 9.9671080	total: 10.8s	remaining: 35.8s
232:	learn: 9.9668357	total: 10.9s	remaining: 35.8s
233:	learn: 9.9666830	total: 10.9s	remaining: 35.8s
234:	learn: 9.9663240	total: 11s	remaining: 35.8s
235:	learn: 9.9656147	total: 11s	remaining: 35.8s
236:	learn: 9.9652333	total: 11.1s	remaining: 35.7s
237:	learn: 9.9648130	total: 11.2s	remaining: 35.7s
238:	learn: 9.9644103	total: 11.2s	remaining: 35.7s
239:	learn: 9.9640228	total: 11.3s	remaining: 35.7s
240:	learn: 9.9636560	total: 11.3s	remaining: 35.6s
241:	learn: 9.9632674	total: 11.4s	remaining: 35.7s
242:	learn: 9.9630775	total: 11.4s	remaining: 35.7s
243:	learn: 9.9627673	total: 11.5s	remaining: 35.6s
244:	learn: 9.9619473	total: 11.6s	remaining: 35.6s
245:	learn: 9.9616444	total: 11.6s	remaining: 35.6s
246:	learn: 9.9613005	total: 11.7s	remaining: 35.6s
247:	learn: 9.9608976	total: 11.7s	remaining: 35.6s
248:	learn: 9.9605223	total: 11.8s	remaining: 35.6s
249:	learn: 9.9601590	total: 11.9s	remaining: 35.6s
250:	learn: 9.9598372	total: 11.9s	remaining: 35.6s
251:	learn: 9.9595783	total: 12s	remaining: 35.5s
252:	learn: 9.9593121	total: 12s	remaining: 35.5s
253:	learn: 9.9588833	total: 12.1s	remaining: 35.5s
254:	learn: 9.9587339	total: 12.1s	remaining: 35.5s
255:	learn: 9.9581527	total: 12.2s	remaining: 35.5s
256:	learn: 9.9576223	total: 12.3s	remaining: 35.4s
257:	learn: 9.9572889	total: 12.3s	remaining: 35.4s
258:	learn: 9.9568015	total: 12.4s	remaining: 35.4s
259:	learn: 9.9564735	total: 12.4s	remaining: 35.4s
260:	learn: 9.9562393	total: 12.5s	remaining: 35.4s
261:	learn: 9.9558837	total: 12.5s	remaining: 35.3s
262:	learn: 9.9554997	total: 12.6s	remaining: 35.3s
263:	learn: 9.9552496	total: 12.7s	remaining: 35.3s
264:	learn: 9.9549342	total: 12.7s	remaining: 35.3s
265:	learn: 9.9545955	total: 12.8s	remaining: 35.2s
266:	learn: 9.9542777	total: 12.8s	remaining: 35.2s
267:	learn: 9.9540381	total: 12.9s	remaining: 35.2s
268:	learn: 9.9537567	total: 12.9s	remaining: 35.2s
269:	learn: 9.9533618	total: 13s	remaining: 35.1s
270:	learn: 9.9530789	total: 13.1s	remaining: 35.1s
271:	learn: 9.9528762	total: 13.1s	remaining: 35.1s
272:	learn: 9.9523987	total: 13.2s	remaining: 35.1s
273:	learn: 9.9520731	total: 13.2s	remaining: 35.1s
274:	learn: 9.9518736	total: 13.3s	remaining: 35.1s
275:	learn: 9.9516217	total: 13.4s	remaining: 35s
276:	learn: 9.9512387	total: 13.4s	remaining: 35s
277:	learn: 9.9509164	total: 13.5s	remaining: 35s
278:	learn: 9.9506850	total: 13.5s	remaining: 35s
279:	learn: 9.9503349	total: 13.6s	remaining: 34.9s
280:	learn: 9.9499548	total: 13.7s	remaining: 34.9s
281:	learn: 9.9496222	total: 13.7s	remaining: 34.9s
282:	learn: 9.9492865	total: 13.8s	remaining: 34.9s
283:	learn: 9.9491487	total: 13.8s	remaining: 34.9s
284:	learn: 9.9489289	total: 13.9s	remaining: 34.8s
285:	learn: 9.9485614	total: 13.9s	remaining: 34.8s
286:	learn: 9.9482412	total: 14s	remaining: 34.8s
287:	learn: 9.9479134	total: 14.1s	remaining: 34.8s
288:	learn: 9.9475600	total: 14.1s	remaining: 34.7s
289:	learn: 9.9473517	total: 14.2s	remaining: 34.7s
290:	learn: 9.9471619	total: 14.2s	remaining: 34.6s
291:	learn: 9.9467948	total: 14.3s	remaining: 34.6s
292:	learn: 9.9464185	total: 14.3s	remaining: 34.6s
293:	learn: 9.9460943	total: 14.4s	remaining: 34.5s
294:	learn: 9.9458126	total: 14.4s	remaining: 34.5s
295:	learn: 9.9453735	total: 14.5s	remaining: 34.5s
296:	learn: 9.9452368	total: 14.6s	remaining: 34.4s
297:	learn: 9.9448577	total: 14.6s	remaining: 34.4s
298:	learn: 9.9444580	total: 14.7s	remaining: 34.4s
299:	learn: 9.9440766	total: 14.7s	remaining: 34.4s
300:	learn: 9.9438352	total: 14.8s	remaining: 34.3s
301:	learn: 9.9433324	total: 14.8s	remaining: 34.3s
302:	learn: 9.9430513	total: 14.9s	remaining: 34.3s
303:	learn: 9.9426530	total: 15s	remaining: 34.2s
304:	learn: 9.9423805	total: 15s	remaining: 34.2s
305:	learn: 9.9420121	total: 15.1s	remaining: 34.2s
306:	learn: 9.9417645	total: 15.1s	remaining: 34.2s
307:	learn: 9.9415130	total: 15.2s	remaining: 34.1s
308:	learn: 9.9411836	total: 15.3s	remaining: 34.1s
309:	learn: 9.9409268	total: 15.3s	remaining: 34.1s
310:	learn: 9.9406633	total: 15.4s	remaining: 34.1s
311:	learn: 9.9403030	total: 15.4s	remaining: 34s
312:	learn: 9.9400088	total: 15.5s	remaining: 34s
313:	learn: 9.9396510	total: 15.5s	remaining: 34s
314:	learn: 9.9394885	total: 15.6s	remaining: 33.9s
315:	learn: 9.9392043	total: 15.7s	remaining: 33.9s
316:	learn: 9.9388622	total: 15.7s	remaining: 33.9s
317:	learn: 9.9385723	total: 15.8s	remaining: 33.8s
318:	learn: 9.9383775	total: 15.8s	remaining: 33.8s
319:	learn: 9.9381571	total: 15.9s	remaining: 33.8s
320:	learn: 9.9378208	total: 15.9s	remaining: 33.7s
321:	learn: 9.9373809	total: 16s	remaining: 33.7s
322:	learn: 9.9370417	total: 16.1s	remaining: 33.7s
323:	learn: 9.9368201	total: 16.1s	remaining: 33.6s
324:	learn: 9.9364647	total: 16.2s	remaining: 33.6s
325:	learn: 9.9361713	total: 16.2s	remaining: 33.6s
326:	learn: 9.9358825	total: 16.3s	remaining: 33.5s
327:	learn: 9.9355818	total: 16.3s	remaining: 33.5s
328:	learn: 9.9353195	total: 16.4s	remaining: 33.4s
329:	learn: 9.9350778	total: 16.4s	remaining: 33.4s
330:	learn: 9.9348107	total: 16.5s	remaining: 33.4s
331:	learn: 9.9343452	total: 16.6s	remaining: 33.3s
332:	learn: 9.9341029	total: 16.6s	remaining: 33.3s
333:	learn: 9.9337405	total: 16.7s	remaining: 33.2s
334:	learn: 9.9335525	total: 16.7s	remaining: 33.2s
335:	learn: 9.9332880	total: 16.8s	remaining: 33.2s
336:	learn: 9.9330752	total: 16.9s	remaining: 33.2s
337:	learn: 9.9327832	total: 16.9s	remaining: 33.1s
338:	learn: 9.9325350	total: 17s	remaining: 33.1s
339:	learn: 9.9321701	total: 17s	remaining: 33.1s
340:	learn: 9.9318207	total: 17.1s	remaining: 33s
341:	learn: 9.9316653	total: 17.1s	remaining: 33s
342:	learn: 9.9313111	total: 17.2s	remaining: 33s
343:	learn: 9.9309627	total: 17.3s	remaining: 32.9s
344:	learn: 9.9306540	total: 17.3s	remaining: 32.9s
345:	learn: 9.9304795	total: 17.4s	remaining: 32.8s
346:	learn: 9.9302147	total: 17.4s	remaining: 32.8s
347:	learn: 9.9299572	total: 17.5s	remaining: 32.8s
348:	learn: 9.9296840	total: 17.5s	remaining: 32.7s
349:	learn: 9.9294485	total: 17.6s	remaining: 32.7s
350:	learn: 9.9291412	total: 17.7s	remaining: 32.7s
351:	learn: 9.9287853	total: 17.7s	remaining: 32.6s
352:	learn: 9.9284646	total: 17.8s	remaining: 32.6s
353:	learn: 9.9280816	total: 17.8s	remaining: 32.5s
354:	learn: 9.9277848	total: 17.9s	remaining: 32.5s
355:	learn: 9.9274997	total: 17.9s	remaining: 32.5s
356:	learn: 9.9270733	total: 18s	remaining: 32.4s
357:	learn: 9.9268703	total: 18.1s	remaining: 32.4s
358:	learn: 9.9265682	total: 18.1s	remaining: 32.4s
359:	learn: 9.9262530	total: 18.2s	remaining: 32.3s
360:	learn: 9.9259932	total: 18.2s	remaining: 32.3s
361:	learn: 9.9257370	total: 18.3s	remaining: 32.2s
362:	learn: 9.9252684	total: 18.4s	remaining: 32.2s
363:	learn: 9.9250636	total: 18.4s	remaining: 32.2s
364:	learn: 9.9247874	total: 18.5s	remaining: 32.2s
365:	learn: 9.9244501	total: 18.6s	remaining: 32.2s
366:	learn: 9.9239570	total: 18.7s	remaining: 32.2s
367:	learn: 9.9236555	total: 18.7s	remaining: 32.2s
368:	learn: 9.9234713	total: 18.8s	remaining: 32.2s
369:	learn: 9.9232925	total: 18.9s	remaining: 32.1s
370:	learn: 9.9231286	total: 18.9s	remaining: 32.1s
371:	learn: 9.9228345	total: 19s	remaining: 32.1s
372:	learn: 9.9226229	total: 19.1s	remaining: 32.1s
373:	learn: 9.9224143	total: 19.1s	remaining: 32s
374:	learn: 9.9219903	total: 19.2s	remaining: 32s
375:	learn: 9.9218563	total: 19.3s	remaining: 32s
376:	learn: 9.9215524	total: 19.4s	remaining: 32.1s
377:	learn: 9.9213719	total: 19.5s	remaining: 32.1s
378:	learn: 9.9210912	total: 19.6s	remaining: 32.1s
379:	learn: 9.9207694	total: 19.7s	remaining: 32.1s
380:	learn: 9.9205723	total: 19.7s	remaining: 32.1s
381:	learn: 9.9201317	total: 19.8s	remaining: 32.1s
382:	learn: 9.9198463	total: 19.9s	remaining: 32s
383:	learn: 9.9196829	total: 19.9s	remaining: 32s
384:	learn: 9.9194740	total: 20s	remaining: 31.9s

array([54.27635385, 17.93233462, 49.1607819 , ...,  6.54922701,
       75.48618706, 57.04843806])

In [33]:
submission_test = pd.read_csv("./inputs/test.csv")
output = pd.DataFrame({'id': submission_test.id, 'Listening_Time_minutes': predictions})
output.to_csv('./outputs/submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!

In [34]:
# Using Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
predictions = model.predict(X_test)
predictions

array([54.740649 , 21.1158756, 51.2549305, ...,  7.7694365, 76.2620053,
       56.2296107])

In [36]:
submission_test = pd.read_csv("./inputs/test.csv")
output = pd.DataFrame({'id': submission_test.id, 'Listening_Time_minutes': predictions})
output.to_csv('./outputs/submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!